In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [6]:
b= np.array([[3.4, 5.6, 6.6],[1.0, 2.4, 5.7]])
b

array([[3.4, 5.6, 6.6],
       [1. , 2.4, 5.7]])

In [7]:
print(b)

[[3.4 5.6 6.6]
 [1.  2.4 5.7]]


In [8]:
#get the dimension
 
a.ndim

1

In [9]:
b.ndim

2

In [10]:
#get shape

a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
#grt type

a.dtype

dtype('int64')

In [13]:
#get size

a.itemsize

8

In [15]:
#get total size

a.nbytes

24

In [16]:
b.nbytes

48

Accessing/Changing specific elements, rows, columns, etc

In [17]:
a = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
#get specific element

a[0,3]

4

In [20]:
a[1, -2]

11

In [21]:
#get a specific row

a[0, :]

array([1, 2, 3, 4, 5, 6])

In [22]:
#get a specific column

a[:, 2]

array([3, 9])

In [23]:
# [startindex:endindex:stepsize]

a[0, 1:4:2]

array([2, 4])

In [24]:
a[1,4]=55
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 55, 12]])

In [25]:
a[:,2] = 3
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  3, 10, 55, 12]])

In [26]:
a[:,3]=[6,6]
a

array([[ 1,  2,  3,  6,  5,  6],
       [ 7,  8,  3,  6, 55, 12]])

In [35]:
#three dimension
m = np.array([[[1,2], [3,4]],[[5,6],[4,5]]])
m

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [4, 5]]])

In [39]:
#get specific element

m[0,1,1]

4

In [43]:
# replace
m[:,1,:]= [[1,1],[0,0]]
m

array([[[1, 2],
        [1, 1]],

       [[5, 6],
        [0, 0]]])

Initialize different types of arrays

In [45]:
#zero matrix

np.zeros((2,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
#one matrix

np.ones((4,5), dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [50]:
#other number

np.full((2,2), 4, dtype='float')

array([[4., 4.],
       [4., 4.]])

In [55]:
np.full_like(a, 7)

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [57]:
# random

np.random.rand(3,3)

array([[0.5267003 , 0.67881896, 0.72513922],
       [0.12264806, 0.44212242, 0.41007581],
       [0.99460978, 0.72724855, 0.91626825]])

In [58]:
np.random.random_sample(a.shape)

array([[0.57065058, 0.11230453, 0.52749359, 0.97004551, 0.89087271,
        0.49839562],
       [0.33561336, 0.73411555, 0.09238493, 0.64259856, 0.49828724,
        0.70111185]])

In [61]:
#random integer values

np.random.randint(9, size=(3,3))

array([[5, 5, 5],
       [3, 8, 5],
       [2, 3, 3]])

In [62]:
np.random.randint(-4,4, size=(3,3))

array([[-2,  3, -2],
       [-4, -3,  2],
       [ 3, -1,  3]])

In [63]:
#identity matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
#repeating an array

arr = np.array([[1,2,3]])
rep = np.repeat(arr, 3, axis=0)
rep

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [68]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [73]:
output[1:-1, 1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Copying arrays

In [74]:
p = np.array([1,2,3])
p

array([1, 2, 3])

In [75]:
q=p
q

array([1, 2, 3])

In [76]:
q[0]=100
q

array([100,   2,   3])

In [77]:
p

array([100,   2,   3])

In [78]:
q = p.copy()
q

array([100,   2,   3])

In [79]:
q[1] = 200
q

array([100, 200,   3])

In [80]:
p

array([100,   2,   3])

In [82]:
# arithmetic operations

x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [83]:
x + 2 

array([3, 4, 5, 6])

In [84]:
x - 2

array([-1,  0,  1,  2])

In [85]:
x * 2

array([2, 4, 6, 8])

In [86]:
x / 2

array([0.5, 1. , 1.5, 2. ])

In [87]:
y = np.array([1, 0, 1, 0])
x + y

array([2, 2, 4, 4])

In [88]:
x ** 2

array([ 1,  4,  9, 16])

In [91]:
#take the sin

np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [92]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [93]:
#linear algebra

r = np.ones((2,3))
r

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
s = np.full((3,2), 2)
s

array([[2, 2],
       [2, 2],
       [2, 2]])

In [97]:
#matrix multiplication

np.matmul(r, s)

array([[6., 6.],
       [6., 6.]])

In [99]:
#find determinant

t = np.identity(3)
np.linalg.det(t)

1.0

In [103]:
#statistics

stats = np.array([[2,3,4],[5,6,7]])
stats

array([[2, 3, 4],
       [5, 6, 7]])

In [105]:
np.min(stats)

2

In [106]:
np.max(stats)

7

In [107]:
np.min(stats, axis=0)

array([2, 3, 4])

In [108]:
np.sum(stats, axis=1)

array([ 9, 18])

In [109]:
#reorganizing arrays

before = np.array([[1,2,3,4],[5,6,7,9]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 9]])

In [115]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 9]]])

In [116]:
#vertical stacking

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [117]:
v1

array([1, 2, 3, 4])

In [118]:
v2

array([5, 6, 7, 8])

In [119]:
#vertical stack

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [127]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [128]:
h2

array([[0., 0.],
       [0., 0.]])

In [129]:
np.hstack((h1,h2,h1))

array([[1., 1., 1., 1., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]])

In [137]:
#load data from file

file_data = np.genfromtxt('array_samples', delimiter=',')
file_data

array([[  1.,   2.,   3.,   4.,  11.,  22.,  33.,  44., 111.,   5.,   6.,
          7.,   9.,  55.,  66.,  77.],
       [ 34.,  45.,  56.,  67.,  78.,  89.,  90.,   1.,  12.,  23., 344.,
        455., 566., 677., 788., 899.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.]])

In [142]:
file_data = file_data.astype('int32')
file_data

array([[  1,   2,   3,   4,  11,  22,  33,  44, 111,   5,   6,   7,   9,
         55,  66,  77],
       [ 34,  45,  56,  67,  78,  89,  90,   1,  12,  23, 344, 455, 566,
        677, 788, 899],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1]], dtype=int32)

In [144]:
#boolean masking and advance indexing

file_data>50

array([[False, False, False, False, False, False, False, False,  True,
        False, False, False, False,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True, False, False,
        False,  True,  True,  True,  True,  True,  True],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False]])

In [145]:
file_data[file_data>50]

array([111,  55,  66,  77,  56,  67,  78,  89,  90, 344, 455, 566, 677,
       788, 899, 999,  78], dtype=int32)

In [147]:
# index with a list in Numpy

v = np.array([1,2,3,4,5,6,7])
v[[0,2,5]]

array([1, 3, 6])

In [148]:
np.any(file_data>50, axis=0)

array([False, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True])

In [149]:
np.all(file_data>50, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [152]:
((file_data>50) & (file_data<100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True,  True,  True],
       [False, False,  True,  True,  True,  True,  True, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False]])